# Étape 1 : Le Builder
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm i

COPY . .
RUN npm run build
# On ne fait pas le prune ici si on veut garder sequelize-cli pour le runner
# Ou on s'assure que sequelize-cli est dans les dependencies (prod)
RUN npm prune --omit=dev

# Étape 2 : Le Runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/config ./config
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/seeders ./seeders

EXPOSE 3000
CMD ["node", "dist/index.js"]
