services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app               # synchroniser le code local
      - /app/node_modules    # garder node_modules dans le container
      - user_uploads:/app/uploads # volume pour les fichiers uploadés
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: ${DB_HOST:-db_postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-mydatabase}
      DB_PORT: ${DB_PORT:-5432}
    depends_on:
      - db

  db:
    container_name: db_postgres
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
  user_uploads:
